### ISSUE TITLE
SDCardDataLoggerWithRTC.ino Time Logic Error

### ISSUE THREAD

**Issue by kd8bxp** [tigoe/DataloggingExamples#1]
1st thank you for the sketch, it saved me a lot of looking but I think I found a logic error,
The way the sketch is written now, it will stop working if/when the seconds are equal or over 49 
IF seconds go from zero to 59, in ten second steps then 49+10 would be 59, seconds will never be greater then 59.  The sketch will hang, and never get pass this.
A better way to do this is with millis()
int currentmillis = 0;

void loop() {
currentmillis = millis();
// if ten seconds have passed:
  if ((currentmillis - lastReadTime) > (interval \* 1000)) {
    lastReadTime = currentmillis;
…….
}
}

So now I'm looking at time past in milliseconds and it shouldn't matter if the seconds is 49 or greater.
currentmillis = 40000 (40 seconds)
lastReadTime = 9000
interval = 30

if ((40000 - 9000) >  (30 \* 1000)) {do stuff} 
or
if (31000 > 30000) {do stuff}

Thanks again.

**Comment by tigoe** [comment]
Although I often use the millis() method, but that example is explicitly about realtime clocks. So I fixed it. Generically, the solution is:

````
if (abs(currentSecond - lastReadTime) >= interval) {
   // do your business then save the second:
   currentSecond = now.second(); // or however your RTC library does it. 
}
````

**Comment by tigoe** [comment]
I often use the millis() method, but since this is explicitly about realtime clocks, the solution needs to be an RTC example. I have an alternative for the RTCZero. library [here](https://github.com/ITPNYU/clock-club/tree/main/Microcontroller_Time_Setting_Methods/RTCInterval), but am still working on it for the Time library.

**Comment by tigoe** [comment]
Updated with [this commit](https://github.com/tigoe/DataloggingExamples/commit/d039e4115d09fbccb808fabc27fe3ae56d470fd9). Thanks for the catch.
