### ISSUE TITLE
Temperature and humidity variables are flipped in the DHT11 example

### ISSUE THREAD

**Issue by aresnick** [tigoe/DataloggingExamples#4]
[Here](https://github.com/tigoe/DataloggingExamples/blob/master/Columbia_Brown_Center_2016/DHT11/DHT11.ino#L38-L39) it seems that the variables have been flipped unwittingly:

```C
float humidity = dht.readTemperature();
float temperature = dht.readHumidity();
```

**Comment by tigoe** [comment]
fixed, thanks.
